#!/usr/bin/env bash
#Bash script that displays: To infinity and beyond indefinitely, sleep 2
i=0
while [ $i -le 3 ]
do
    trap "echo I am invincible!!!" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
