#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd. The script should only display: username, user id, Home directory path for the user

while IFS= read -r L
do
    echo "$L" | cut -d':' -f1,4,7
done < /etc/passwd
